server:
  port: 8071 #配置程序端口,默认为8080

#logging:
#  config: classpath:logback/logback-dev.xml

#swagger.enable: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imas41?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: postgres
    password: ROOT
    driver-class-name: org.postgresql.Driver
    druid: # 2.2.3开始提供全局druid参数，以下是默认值和druid原生保持一致
      initial-size: 3
      max-active: 8
      min-idle: 3
      max-wait: -1
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 0
      validation-query: select 1
      validation-query-timeout: -1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      max-open-prepared-statements: 100
      filters: stat,wall
      share-prepared-statements: true