spring:
  profiles:
    active: dev


mybatis-plus:
  check-config-location: true  #启动时检查MyBatis XML文件的存在
  executor-type: reuse #复用预处理语句
  configuration:
    map-underscore-to-camel-case: true #开启自动驼峰命名规则
    auto-mapping-unknown-column-behavior: warning #自动映射时未知列或未知属性处理策略，以日志打印警告信息
    cache-enabled: true #全局开启所有映射器已经配置的任何缓存
    call-setters-on-nulls: false #指定当结果集中值为null时不调用映射对象的Setter
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql

#mapper-locations: classpath:/mapper/**/*Mapper.xml
